version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medcpt-api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - medcpt-network
    restart: unless-stopped

networks:
  medcpt-network:
    driver: bridge
